// <auto-generated />
using System;
using InLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923155431_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InLab.Models.Area", b =>
                {
                    b.Property<int>("IdAre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_are");

                    b.Property<string>("NomeAre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_are");

                    b.HasKey("IdAre");

                    b.ToTable("area");
                });

            modelBuilder.Entity("InLab.Models.Calibracao", b =>
                {
                    b.Property<int>("IdCal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cal");

                    b.Property<DateTime>("DataCal")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_cal");

                    b.Property<int>("IdDet")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_det");

                    b.HasKey("IdCal");

                    b.HasIndex("IdDet");

                    b.ToTable("calibracao");
                });

            modelBuilder.Entity("InLab.Models.Detector", b =>
                {
                    b.Property<int>("IdAde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ade");

                    b.Property<string>("CadastroDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cadastro_det");

                    b.Property<DateTime?>("DataCacDet")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_caç_det");

                    b.Property<DateTime?>("DataCoDet")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_co_det");

                    b.Property<string>("FabricanteDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fabricante_det");

                    b.Property<int>("IdAre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_are");

                    b.Property<string>("ModeloDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modelo_det");

                    b.Property<string>("SerialDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_det");

                    b.Property<string>("StatusCoDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status_co_det");

                    b.Property<string>("StatusUsoDet")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status_uso_det");

                    b.HasKey("IdAde");

                    b.HasIndex("IdAre");

                    b.ToTable("detector");
                });

            modelBuilder.Entity("InLab.Models.Calibracao", b =>
                {
                    b.HasOne("InLab.Models.Detector", "Detector")
                        .WithMany("Calibracoes")
                        .HasForeignKey("IdDet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detector");
                });

            modelBuilder.Entity("InLab.Models.Detector", b =>
                {
                    b.HasOne("InLab.Models.Area", "Area")
                        .WithMany("Detectores")
                        .HasForeignKey("IdAre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("InLab.Models.Area", b =>
                {
                    b.Navigation("Detectores");
                });

            modelBuilder.Entity("InLab.Models.Detector", b =>
                {
                    b.Navigation("Calibracoes");
                });
#pragma warning restore 612, 618
        }
    }
}
